name: Deploy

on:
  push:
    branches:
      - master
jobs: 
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm i   
        
        #Env  
        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1
          with:
              envkey_IS_DEVELOP: false
              envkey_BASE_URL: ${{ secrets.BASE_URL }}
              envkey_API_URL: ${{ secrets.SERVER_URL }}
              file_name: .env    
        #Build      
        - name: Build
          run: npm run build           
        #Copy
        - name: copy file via ssh key
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            port: ${{ secrets.PORT }}
            key: ${{ secrets.SSH_KEY }}
            #passphrase: ${{ secrets.PASSPHRASE }}
            source: ".nuxt"
            target: "../var/www/boro.digital/frontend/" 
            #source: "dist"
            #target: "../var/www/boro.digital/frontend/" 
        # Deploy  
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            #passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd /var/www/boro.digital/frontend/
                git pull
                npm i
                pm2 restart boro
        - name: send custom message
          uses: appleboy/telegram-action@master
          with:
             to: ${{ secrets.TELEGRAM_TO }}
             token: ${{ secrets.TELEGRAM_TOKEN }}
             message: BORO.DIGITAL | Deploy workflow done
