name: Deploy

on:
  push:
    branches:
      - development
jobs: 
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm i   
        - name: Generate
          run: npm run generate
        # Build
        #- name: Run npm
        #  run: npm i
        #- name: Run CI
        #  run: npm ci
        #- name: Run build
        #  run: npm run build
          #env:
            #NEXT_PUBLIC_BASE_URL: ${{ secrets.SERVER_URL }}
            #NEXT_PUBLIC_ORIGIN_URL: https://boro.digital/
        # Env  
        #- name: Make envfile
        #  uses: SpicyPizza/create-envfile@v1
        #  with:
        #      envkey_IS_DEVELOP: false
              #envkey_RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
              #file_name: .env     
        #Copy
        - name: copy file via ssh key
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            port: ${{ secrets.PORT }}
            key: ${{ secrets.SSH_KEY }}
            #passphrase: ${{ secrets.PASSPHRASE }}
            #source: ".nuxt"
            #target: "../var/www/boro.digital/frontend/" 
            source: "dist"
            target: "../var/www/boro.digital/development/" 
        # Deploy  
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            #passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd /var/www/boro.digital/development/
                git pull
                npm i
        - name: send custom message
          uses: appleboy/telegram-action@master
          with:
             to: ${{ secrets.TELEGRAM_TO }}
             token: ${{ secrets.TELEGRAM_TOKEN }}
             message: BORO.DIGITAL | Deploy workflow done. Dev
